#create a new kubernetes namespace
apiVersion: v1
kind: Namespace
metadata:
  name: wso2

---
#create a new service account in wso2 kubernetes namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wso2svc-account
  namespace: wso2