# Copyright (c) 2019, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
wso2:
  mysql:
    enabled: true
    host: wso2is-rdbms-service-mysql
    username: wso2carbon
    password: wso2carbon
    driverClass: com.mysql.jdbc.Driver
    validationQuery: "SELECT 1"
  subscription:
    username: ""
    password: ""
  deployment:
    wso2is:
      imageName: "wso2is"
      imageTag: "5.8.0"
      replicas: 1
      minReadySeconds: 30
      strategy:
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0
      livenessProbe:
        initialDelaySeconds: 250
        periodSeconds: 10
      readinessProbe:
        initialDelaySeconds: 250
        periodSeconds: 10
      resources:
        # These are the minimum resource recommendations for running WSO2 Identity server profiles
        # as per official documentation (https://docs.wso2.com/display/IS580/Installation+Prerequisites).
        requests:
          memory: "2Gi"
          cpu: "2000m"
        limits:
          memory: "4Gi"
          cpu: "4000m"
      imagePullPolicy: Always
  centralizedLogging:
    enabled: false
    logstash:
      imageTag: 7.2.0
      elasticsearch:
        host: wso2-elasticsearch-master
        username: "elastic"
        password: "changeme"
      indexNodeID:
        wso2ISNode: "wso2is-node"

kubernetes:
  svcaccount: "wso2svc-account"
