
apiVersion: v1
kind: Service
metadata:
  name: wso2is-is-service
  namespace: "$ns.k8s&wso2.is"
  labels:
    deployment: wso2is-is
spec:
  selector:
    deployment: wso2is-is
  type: NodePort
  ports:
    - name: servlet-http
      port: 9763
      targetPort: 9763
      protocol: TCP
    - name: servlet-https
      port: 9443
      targetPort: 9443
      protocol: TCP
      nodePort: "$nodeport.k8s.&.1.wso2is"
---
