
apiVersion: v1
kind: Service
metadata:
  name: wso2is-rdbms-service
  namespace: "$ns.k8s&wso2.is"
spec:
  type: ClusterIP
  selector:
    deployment: wso2is-mysql
  ports:
    - name: mysql-port
      port: 3306
      targetPort: 3306
      protocol: TCP
---
