# Copyright (c) 2018, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wso2is-with-analytics-is-analytics-worker-deployment
  namespace : {{ .Release.Namespace }}
spec:
  replicas: {{ default 1 .Values.wso2.deployment.wso2isAnalyticsWorker.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: {{ default 1 .Values.wso2.deployment.wso2isAnalyticsWorker.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ default 0 .Values.wso2.deployment.wso2isAnalyticsWorker.strategy.rollingUpdate.maxUnavailable }}
    type: RollingUpdate
  selector:
    matchLabels:
      deployment: wso2is-with-analytics-is-analytics-worker
  template:
    metadata:
      labels:
        deployment: wso2is-with-analytics-is-analytics-worker
    spec:
      initContainers:
      - name: init-is-db
        image: busybox:1.31
        command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z wso2is-rdbms-service-mysql 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL Server has started";']
      {{ if .Values.wso2.centralizedLogging.enabled }}
      - name: init-logstash-plugins-install
        image: docker.elastic.co/logstash/logstash:{{ default "7.2.0" .Values.wso2.centralizedLogging.logstash.imageTag }}
        command:
          - /bin/bash
          - "-c"
          - |
            set -e
            ./bin/logstash-plugin install logstash-codec-multiline logstash-filter-grok
        volumeMounts:
          - name: shared-plugins
            mountPath: /usr/share/logstash/plugins/
      - name: init-elasticsearch
        image: busybox:1.31
        command: ['sh', '-c', 'echo -e "Checking for the availability of Elasticsearch Server deployment"; while ! nc -z {{ default "wso2-elasticsearch-master" .Values.wso2.centralizedLogging.logstash.elasticsearch.host }} 9200; do sleep 1; printf "-"; done; echo -e "  >> Elasticsearch server has started";']
      {{ end }}
      containers:
      - name: wso2is-with-analytics-is-analytics-worker
        {{- if .Values.wso2.deployment.wso2isAnalyticsWorker.dockerRegistry }}
        image: {{ .Values.wso2.deployment.wso2isAnalyticsWorker.dockerRegistry }}/{{ default "wso2is-analytics-worker" .Values.wso2.deployment.wso2isAnalyticsWorker.imageName }}
        {{- $tag := .Values.wso2.deployment.wso2isAnalyticsWorker.imageTag }}
        {{- if not (eq $tag "") }}{{- printf ":%s" $tag -}}{{- end }}
        {{- else if or (eq .Values.wso2.subscription.username "") (eq .Values.wso2.subscription.password "") }}
        image: wso2/{{ default "wso2is-analytics-worker" .Values.wso2.deployment.wso2isAnalyticsWorker.imageName }}:{{ default "5.8.0" .Values.wso2.deployment.wso2isAnalyticsWorker.imageTag }}
        {{- else }}
        image: docker.wso2.com/{{ default "wso2is-analytics-worker" .Values.wso2.deployment.wso2isAnalyticsWorker.imageName }}:{{ default "5.8.0" .Values.wso2.deployment.wso2isAnalyticsWorker.imageTag }}
        {{- end }}
        env:
        -
          name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          requests:
            memory: {{ .Values.wso2.deployment.wso2isAnalyticsWorker.resources.requests.memory }}
            cpu: {{ .Values.wso2.deployment.wso2isAnalyticsWorker.resources.requests.cpu }}
          limits:
            memory: {{ .Values.wso2.deployment.wso2isAnalyticsWorker.resources.limits.memory }}
            cpu: {{ .Values.wso2.deployment.wso2isAnalyticsWorker.resources.limits.cpu }}
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - nc -z localhost 9091
          initialDelaySeconds: {{ default 200 .Values.wso2.deployment.wso2isAnalyticsWorker.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ default 10 .Values.wso2.deployment.wso2isAnalyticsWorker.livenessProbe.periodSeconds }}
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - nc -z localhost 7712
          initialDelaySeconds: {{ default 200 .Values.wso2.deployment.wso2isAnalyticsWorker.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ default 10 .Values.wso2.deployment.wso2isAnalyticsWorker.readinessProbe.periodSeconds }}
        lifecycle:
          preStop:
            exec:
              command:  ['sh', '-c', '${WSO2_SERVER_HOME}/bin/worker.sh stop']
        imagePullPolicy: {{ default "Always" .Values.wso2.deployment.wso2isAnalyticsWorker.imagePullPolicy }}
        securityContext:
          runAsUser: 802
        ports:
          -
            containerPort: 9090
            protocol: TCP
          -
            containerPort: 9091
            protocol: TCP
          -
            containerPort: 9543
            protocol: TCP
          -
            containerPort: 9711
            protocol: TCP
          -
            containerPort: 9611
            protocol: TCP
          -
            containerPort: 7712
            protocol: TCP
          -
            containerPort: 7612
            protocol: TCP
          -
            containerPort: 7070
            protocol: TCP
          -
            containerPort: 7443
            protocol: TCP
        volumeMounts:
        - name: is-analytics-worker-conf
          mountPath: /home/wso2carbon/wso2-config-volume/conf/worker
      {{ if .Values.wso2.centralizedLogging.enabled }}
        - name: shared-logs
          mountPath: /home/wso2carbon/wso2is-analytics-5.8.0/wso2/worker/logs
      - name: wso2is-with-analytics-is-analytics-worker-logstash
        image: docker.elastic.co/logstash/logstash:{{ default "7.2.0" .Values.wso2.centralizedLogging.logstash.imageTag }}
        volumeMounts:
          - name: shared-logs
            mountPath: /usr/share/logstash/wso2-logs/
          - name: logstash-yml
            mountPath: /usr/share/logstash/config/logstash.yml
            subPath: logstash.yml
          - name: c5-logstash-conf
            mountPath: /usr/share/logstash/pipeline/logstash.conf
            subPath: logstash.conf
          - name: shared-plugins
            mountPath: /usr/share/logstash/plugins/
        env:
          - name: NODE_ID
            value: {{ default "wso2is-node" .Values.wso2.centralizedLogging.logstash.indexNodeID.wso2ISNode }}
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: ELASTICSEARCH_USERNAME
            valueFrom:
              secretKeyRef:
                name: logstash-elasticsearch-creds
                key: username
          - name: ELASTICSEARCH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: logstash-elasticsearch-creds
                key: password
          - name: ELASTICSEARCH_HOST
            value: {{ default "wso2-elasticsearch-master" .Values.wso2.centralizedLogging.logstash.elasticsearch.host }}
      {{ end }}
      serviceAccountName: {{ .Values.kubernetes.svcaccount }}
      {{ if and (not (eq .Values.wso2.subscription.username "")) (not (eq .Values.wso2.subscription.password "")) }}
      imagePullSecrets:
      - name: wso2creds
      {{ end }}
      volumes:
      - name: is-analytics-worker-conf
        configMap:
          name: is-analytics-worker-conf
      {{ if .Values.wso2.centralizedLogging.enabled }}
      - name: shared-logs
        emptyDir: {}
      - name: logstash-yml
        configMap:
          name: logstash-yml
      - name: c5-logstash-conf
        configMap:
          name: c5-logstash-conf
      - name: shared-plugins
        emptyDir: {}
      - name: logstash-elasticsearch-creds
        secret:
          secretName: logstash-elasticsearch-creds
      {{ end }}
